CREATE TABLE IF NOT EXISTS EQUIPOS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  MARCA VARCHAR(100) NOT NULL,
  PRECIO VARCHAR(7) NOT NULL,
  CANTIDAD INTEGER NOT NULL
 );

INSERT INTO EQUIPOS (MARCA, PRECIO, CANTIDAD) VALUES('Samsung S20', '599.990', 10);
INSERT INTO EQUIPOS (MARCA, PRECIO, CANTIDAD) VALUES('Huawei P40 Pro', '839.760', 5);
INSERT INTO EQUIPOS (MARCA, PRECIO, CANTIDAD) VALUES('Motorola Moto G8', '179.880', 0);
INSERT INTO EQUIPOS (MARCA, PRECIO, CANTIDAD) VALUES('Xiaomi Redmi Note 8', '143.880', 20);
INSERT INTO EQUIPOS (MARCA, PRECIO, CANTIDAD) VALUES('Apple iPhone 11 Pro', '887.760', 10);
INSERT INTO EQUIPOS (MARCA, PRECIO, CANTIDAD) VALUES('Nokia 5.1 Plus', '77.880', 6);
INSERT INTO EQUIPOS (MARCA, PRECIO, CANTIDAD) VALUES('LG K50s', '119.880', 2);
INSERT INTO EQUIPOS (MARCA, PRECIO, CANTIDAD) VALUES('ZTE Blade A7', '59.880', 30);